CREATE TABLE block(hash TEXT PRIMARY KEY, s3key TEXT);

CREATE TABLE chunk(cid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, frid INTEGER NOT NULL, chunknumber INTEGER NOT NULL, hash TEXT NOT NULL);

CREATE TABLE 'commit'(cid INTEGER PRIMARY KEY AUTOINCREMENT, projectid INTEGER, userid TEXT, comment TEXT, numfiles INTEGER, timestamp DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE file(fid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pid INTEGER NOT NULL, path TEXT NOT NULL);

CREATE TABLE filerevision(frid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, fid INTEGER NOT NULL, commitid INTEGER NOT NULL, numchunks INTEGER, changetype INTEGER);

CREATE TABLE project(pid INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, teamid INTEGER, basecommit INTEGER);

CREATE TABLE projectpermission(userid TEXT, projectid INTEGER, level INTEGER);

CREATE TABLE team(teamid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, ownerid TEXT, planid INTEGER);

CREATE TABLE teampermission (userid TEXT, teamid TEXT, level INTEGER, PRIMARY KEY (userid, teamid));