// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcgen

import (
	"database/sql"
)

type Block struct {
	Hash  string
	S3key string
	Size  int64
}

type Commit struct {
	Commitid  int64
	Projectid int64
	Userid    string
	Comment   interface{}
	Numfiles  int64
	Cno       sql.NullInt64
	Timestamp int64
}

type File struct {
	Projectid   int64
	Path        string
	Locked      int64
	Lockownerid sql.NullString
}

type Filerevision struct {
	Frid       int64
	Projectid  int64
	Path       string
	Commitid   int64
	Hash       string
	Frno       sql.NullInt64
	Changetype int64
}

type Project struct {
	Projectid int64
	Title     string
	Teamid    int64
}

type Projectpermission struct {
	Userid    string
	Projectid int64
	Level     int64
}

type Team struct {
	Teamid int64
	Name   string
	Planid sql.NullInt64
}

type Teampermission struct {
	Userid string
	Teamid int64
	Level  int64
}
