# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    # Ensure sqlc is installed
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.27.0'
    - name: Verify sqlc
      run: sqlc diff
    - name: Build backend
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
